### ISSUE TITLE
API Registry fails to testing

### ISSUE THREAD

**Issue by davsclaus** [fabric8io/quickstarts#111]
Doing a mvn clean install on quickstarts fails in the api registry module.

```
Results :

Failed tests:
  ApiRegistryTest.before:61 Jetty Server could not be started
```

```
org.jboss.weld.exceptions.DeploymentException: Exception List with 1 exceptions:
Exception 0 :
javax.ws.rs.core.UriBuilderException: URI can not be built
	at org.apache.cxf.jaxrs.impl.UriBuilderImpl.doBuild(UriBuilderImpl.java:105)
	at org.apache.cxf.jaxrs.impl.UriBuilderImpl.buildFromEncoded(UriBuilderImpl.java:230)
	at org.apache.cxf.jaxrs.client.AbstractClient.getCurrentURI(AbstractClient.java:270)
	at org.apache.cxf.jaxrs.client.JAXRSClientFactory.fromClient(JAXRSClientFactory.java:352)
	at org.apache.cxf.jaxrs.client.JAXRSClientFactory.fromClient(JAXRSClientFactory.java:340)
	at io.fabric8.kubernetes.api.KubernetesFactory.createWebClient(KubernetesFactory.java:108)
	at io.fabric8.kubernetes.api.KubernetesFactory.createKubernetes(KubernetesFactory.java:91)
	at io.fabric8.kubernetes.jolokia.JolokiaClients.<init>(JolokiaClients.java:51)
	at io.fabric8.api.registry.ApiFinder.<init>(ApiFinder.java:77)
```

**Comment by davsclaus** [comment]
Tests works now
