### ISSUE TITLE
camel-cdi fails to startup

### ISSUE THREAD

**Issue by jstrachan** [fabric8io/quickstarts#24]
mvn test-compile exec:java generates:
```
[INFO] --- exec-maven-plugin:1.2.1:java (default-cli) @ java-camel-cdi ---
2014-11-13 07:01:18,455 [cdi.Main.main()] INFO  Version                        - WELD-000900: 2.2.5 (Final)
2014-11-13 07:01:19,719 [cdi.Main.main()] INFO  Bootstrap                      - WELD-000101: Transactional services not available. Injection of @Inject UserTransaction not available. Transactional observers will be invoked synchronously.
2014-11-13 07:01:20,254 [cdi.Main.main()] WARN  Interceptor                    - WELD-001700: Interceptor annotation class javax.ejb.PostActivate not found, interception based on it is not enabled
2014-11-13 07:01:20,255 [cdi.Main.main()] WARN  Interceptor                    - WELD-001700: Interceptor annotation class javax.ejb.PrePassivate not found, interception based on it is not enabled
2014-11-13 07:01:20,969 [cdi.Main.main()] WARN  Event                          - WELD-000411: Observer method [BackedAnnotatedMethod] protected org.apache.camel.cdi.internal.CamelExtension.detectRouteBuilders(@Observes ProcessAnnotatedType<Object>) receives events for all annotated types. Consider restricting events using @WithAnnotations or a generic type with bounds.
2014-11-13 07:01:20,999 [cdi.Main.main()] WARN  Event                          - WELD-000411: Observer method [BackedAnnotatedMethod] protected org.apache.deltaspike.core.impl.message.MessageBundleExtension.detectInterfaces(@Observes ProcessAnnotatedType<Object>) receives events for all annotated types. Consider restricting events using @WithAnnotations or a generic type with bounds.
2014-11-13 07:01:21,058 [cdi.Main.main()] WARN  Event                          - WELD-000411: Observer method [BackedAnnotatedMethod] protected org.apache.deltaspike.core.impl.exclude.extension.ExcludeExtension.vetoBeans(@Observes ProcessAnnotatedType<Object>, BeanManager) receives events for all annotated types. Consider restricting events using @WithAnnotations or a generic type with bounds.
Nov 13, 2014 7:01:21 AM org.apache.deltaspike.core.util.ClassDeactivationUtils cacheResult
INFO: class: org.apache.deltaspike.core.impl.scope.DeltaSpikeContextExtension activated=true
Nov 13, 2014 7:01:21 AM org.apache.deltaspike.core.util.ClassDeactivationUtils cacheResult
INFO: class: org.apache.deltaspike.core.impl.config.ConfigurationExtension activated=true
Nov 13, 2014 7:01:21 AM org.apache.deltaspike.core.util.ClassDeactivationUtils cacheResult
INFO: class: org.apache.deltaspike.core.impl.exception.control.extension.ExceptionControlExtension activated=true
Nov 13, 2014 7:01:21 AM org.apache.deltaspike.core.util.ClassDeactivationUtils cacheResult
INFO: class: org.apache.deltaspike.core.impl.message.MessageBundleExtension activated=true
Nov 13, 2014 7:01:21 AM org.apache.deltaspike.core.util.ClassDeactivationUtils cacheResult
INFO: class: org.apache.deltaspike.core.impl.message.NamedMessageBundleInvocationHandler activated=true
Nov 13, 2014 7:01:21 AM org.apache.deltaspike.core.util.ClassDeactivationUtils cacheResult
INFO: class: org.apache.deltaspike.core.impl.exclude.extension.ExcludeExtension activated=true
Nov 13, 2014 7:01:21 AM org.apache.deltaspike.core.util.ClassDeactivationUtils cacheResult
INFO: class: org.apache.deltaspike.core.impl.exclude.CustomProjectStageBeanFilter activated=true
Nov 13, 2014 7:01:21 AM org.apache.deltaspike.core.util.ClassDeactivationUtils cacheResult
INFO: class: org.apache.deltaspike.core.impl.exclude.GlobalAlternative activated=true
Nov 13, 2014 7:01:21 AM org.apache.deltaspike.core.util.ClassDeactivationUtils cacheResult
INFO: class: org.apache.deltaspike.core.impl.jmx.MBeanExtension activated=true
Nov 13, 2014 7:01:21 AM org.apache.deltaspike.core.util.ProjectStageProducer initProjectStage
INFO: Computed the following DeltaSpike ProjectStage: Production
2014-11-13 07:01:23,093 [weld-worker-8  ] WARN  Validator                      - WELD-001473: javax.enterprise.inject.spi.Bean implementation org.apache.camel.cdi.internal.CamelContextBean@3b5689c6 declared a normal scope but does not implement javax.enterprise.inject.spi.PassivationCapable. It won't be possible to inject this bean into a bean with a passivating scope (@SessionScoped, @ConversationScoped). This can be fixed by assigning the Bean implementation a unique id by implementing the PassivationCapable interface.
2014-11-13 07:01:23,816 [cdi.Main.main()] INFO  CdiCamelContext                - Apache Camel 2.14.0 (CamelContext: myCdiCamelContext) is starting
2014-11-13 07:01:23,818 [cdi.Main.main()] INFO  ManagedManagementStrategy      - JMX is enabled
2014-11-13 07:01:24,062 [cdi.Main.main()] INFO  DefaultTypeConverter           - Loaded 178 type converters
2014-11-13 07:01:24,115 [cdi.Main.main()] INFO  CdiCamelContext                - AllowUseOriginalMessage is enabled. If access to the original message is not needed, then its recommended to turn this option off as it may improve performance.
2014-11-13 07:01:24,115 [cdi.Main.main()] INFO  CdiCamelContext                - StreamCaching is not in use. If using streams then its recommended to enable stream caching. See more details at http://camel.apache.org/stream-caching.html
2014-11-13 07:01:24,115 [cdi.Main.main()] INFO  CdiCamelContext                - Total 0 routes, of which 0 is started.
2014-11-13 07:01:24,116 [cdi.Main.main()] INFO  CdiCamelContext                - Apache Camel 2.14.0 (CamelContext: myCdiCamelContext) started in 0.301 seconds
2014-11-13 07:01:24,123 [cdi.Main.main()] INFO  MainSupport                    - Apache Camel 2.14.0 stopping
[WARNING]
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:297)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.jboss.weld.exceptions.DeploymentException: Exception List with 1 exceptions:
Exception 0 :
org.jboss.weld.exceptions.IllegalStateException: WELD-000143: Container lifecycle event method invoked outside of extension observer method invocation.
	at org.jboss.weld.bootstrap.events.ContainerEvent.checkWithinObserverNotification(ContainerEvent.java:61)
	at org.jboss.weld.bootstrap.events.ProcessAnnotatedTypeImpl.getAnnotatedType(ProcessAnnotatedTypeImpl.java:56)
	at org.apache.camel.cdi.internal.CamelContextConfig.configure(CamelContextConfig.java:47)
	at org.apache.camel.cdi.internal.CamelContextBean.configureCamelContext(CamelContextBean.java:131)
	at org.apache.camel.cdi.internal.CamelExtension.startConsumeBeans(CamelExtension.java:231)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.jboss.weld.injection.MethodInjectionPoint.invokeOnInstanceWithSpecialValue(MethodInjectionPoint.java:90)
	at org.jboss.weld.event.ObserverMethodImpl.sendEvent(ObserverMethodImpl.java:271)
	at org.jboss.weld.event.ExtensionObserverMethodImpl.sendEvent(ExtensionObserverMethodImpl.java:121)
	at org.jboss.weld.event.ObserverMethodImpl.sendEvent(ObserverMethodImpl.java:258)
	at org.jboss.weld.event.ObserverMethodImpl.notify(ObserverMethodImpl.java:237)
	at org.jboss.weld.event.ObserverNotifier.notifyObserver(ObserverNotifier.java:174)
	at org.jboss.weld.event.ObserverNotifier.notifyObservers(ObserverNotifier.java:133)
	at org.jboss.weld.event.ObserverNotifier.fireEvent(ObserverNotifier.java:107)
	at org.jboss.weld.bootstrap.events.AbstractContainerEvent.fire(AbstractContainerEvent.java:54)
	at org.jboss.weld.bootstrap.events.AbstractDeploymentContainerEvent.fire(AbstractDeploymentContainerEvent.java:35)
	at org.jboss.weld.bootstrap.events.AfterDeploymentValidationImpl.fire(AfterDeploymentValidationImpl.java:28)
	at org.jboss.weld.bootstrap.WeldStartup.validateBeans(WeldStartup.java:437)
	at org.jboss.weld.bootstrap.WeldBootstrap.validateBeans(WeldBootstrap.java:90)
	at org.jboss.weld.environment.se.Weld.initialize(Weld.java:148)
	at org.apache.deltaspike.cdise.weld.WeldContainerControl.boot(WeldContainerControl.java:65)
	at org.apache.camel.cdi.Main.doStart(Main.java:122)
	at org.apache.camel.support.ServiceSupport.start(ServiceSupport.java:61)
	at org.apache.camel.main.MainSupport.run(MainSupport.java:149)
	at org.apache.camel.main.MainSupport.run(MainSupport.java:353)
	at org.apache.camel.cdi.Main.main(Main.java:49)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:297)
	at java.lang.Thread.run(Thread.java:745)

	at org.jboss.weld.bootstrap.events.AbstractDeploymentContainerEvent.fire(AbstractDeploymentContainerEvent.java:37)
	at org.jboss.weld.bootstrap.events.AfterDeploymentValidationImpl.fire(AfterDeploymentValidationImpl.java:28)
	at org.jboss.weld.bootstrap.WeldStartup.validateBeans(WeldStartup.java:437)
	at org.jboss.weld.bootstrap.WeldBootstrap.validateBeans(WeldBootstrap.java:90)
	at org.jboss.weld.environment.se.Weld.initialize(Weld.java:148)
	at org.apache.deltaspike.cdise.weld.WeldContainerControl.boot(WeldContainerControl.java:65)
	at org.apache.camel.cdi.Main.doStart(Main.java:122)
	at org.apache.camel.support.ServiceSupport.start(ServiceSupport.java:61)
	at org.apache.camel.main.MainSupport.run(MainSupport.java:149)
	at org.apache.camel.main.MainSupport.run(MainSupport.java:353)
	at org.apache.camel.cdi.Main.main(Main.java:49)
	... 6 more
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 12.279s
[INFO] Finished at: Thu Nov 13 07:01:24 GMT 2014
[INFO] Final Memory: 27M/228M
[INFO] ------------------------------------------------------------------------
[WARNING] The requested profile "docker-host" could not be activated because it does not exist.
[ERROR] Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.2.1:java (default-cli) on project java-camel-cdi: An exception occured while executing the Java class. null: InvocationTargetException: Exception List with 1 exceptions:
[ERROR] Exception 0 :
[ERROR] org.jboss.weld.exceptions.IllegalStateException: WELD-000143: Container lifecycle event method invoked outside of extension observer method invocation.
[ERROR] at org.jboss.weld.bootstrap.events.ContainerEvent.checkWithinObserverNotification(ContainerEvent.java:61)
[ERROR] at org.jboss.weld.bootstrap.events.ProcessAnnotatedTypeImpl.getAnnotatedType(ProcessAnnotatedTypeImpl.java:56)
[ERROR] at org.apache.camel.cdi.internal.CamelContextConfig.configure(CamelContextConfig.java:47)
[ERROR] at org.apache.camel.cdi.internal.CamelContextBean.configureCamelContext(CamelContextBean.java:131)
[ERROR] at org.apache.camel.cdi.internal.CamelExtension.startConsumeBeans(CamelExtension.java:231)
[ERROR] at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[ERROR] at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
[ERROR] at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[ERROR] at java.lang.reflect.Method.invoke(Method.java:606)
[ERROR] at org.jboss.weld.injection.MethodInjectionPoint.invokeOnInstanceWithSpecialValue(MethodInjectionPoint.java:90)
[ERROR] at org.jboss.weld.event.ObserverMethodImpl.sendEvent(ObserverMethodImpl.java:271)
[ERROR] at org.jboss.weld.event.ExtensionObserverMethodImpl.sendEvent(ExtensionObserverMethodImpl.java:121)
[ERROR] at org.jboss.weld.event.ObserverMethodImpl.sendEvent(ObserverMethodImpl.java:258)
[ERROR] at org.jboss.weld.event.ObserverMethodImpl.notify(ObserverMethodImpl.java:237)
[ERROR] at org.jboss.weld.event.ObserverNotifier.notifyObserver(ObserverNotifier.java:174)
[ERROR] at org.jboss.weld.event.ObserverNotifier.notifyObservers(ObserverNotifier.java:133)
[ERROR] at org.jboss.weld.event.ObserverNotifier.fireEvent(ObserverNotifier.java:107)
[ERROR] at org.jboss.weld.bootstrap.events.AbstractContainerEvent.fire(AbstractContainerEvent.java:54)
[ERROR] at org.jboss.weld.bootstrap.events.AbstractDeploymentContainerEvent.fire(AbstractDeploymentContainerEvent.java:35)
[ERROR] at org.jboss.weld.bootstrap.events.AfterDeploymentValidationImpl.fire(AfterDeploymentValidationImpl.java:28)
[ERROR] at org.jboss.weld.bootstrap.WeldStartup.validateBeans(WeldStartup.java:437)
[ERROR] at org.jboss.weld.bootstrap.WeldBootstrap.validateBeans(WeldBootstrap.java:90)
[ERROR] at org.jboss.weld.environment.se.Weld.initialize(Weld.java:148)
[ERROR] at org.apache.deltaspike.cdise.weld.WeldContainerControl.boot(WeldContainerControl.java:65)
[ERROR] at org.apache.camel.cdi.Main.doStart(Main.java:122)
[ERROR] at org.apache.camel.support.ServiceSupport.start(ServiceSupport.java:61)
[ERROR] at org.apache.camel.main.MainSupport.run(MainSupport.java:149)
[ERROR] at org.apache.camel.main.MainSupport.run(MainSupport.java:353)
[ERROR] at org.apache.camel.cdi.Main.main(Main.java:49)
[ERROR] at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[ERROR] at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
[ERROR] at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[ERROR] at java.lang.reflect.Method.invoke(Method.java:606)
[ERROR] at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:297)
[ERROR] at java.lang.Thread.run(Thread.java:745)
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
2014-11-13 07:01:24,507 [Thread-3       ] INFO  MainSupport$HangupInterceptor  - Received hang up - stopping the main instance.
```

**Comment by davsclaus** [comment]
Works now for a while then ;)
