### ISSUE TITLE
Karaf 4 quickstarts fail to build docker image

### ISSUE THREAD

**Issue by jimmidyson** [fabric8io/quickstarts#644]
This is preventing quickstarts release.

Running `mvn clean install -Pdocker-build` returns:

```
[ERROR] Failed to execute goal org.jolokia:docker-maven-plugin:0.13.2:build (default-cli) on project quickstart-karaf4-camellog: Failed to create assembly for docker image: Error creating assembly archive docker: Failed to read filesystem attributes for: /home/jdyson/projects/fabric8-quickstarts/quickstarts/karaf4/camel-log/target/quickstart-karaf4-camellog-2.3-SNAPSHOT.tar.gz with mode dir -> [Help 1]
```

**Comment by jimmidyson** [comment]
OK I should read... supposed to run:

    mvn clean install karaf:assembly karaf:archive docker:build

This should be in the docker build profile I guess.

**Comment by jimmidyson** [comment]
@dhirajsb Does this require fixes that in `karaf-maven-plugin` 4.0.1-SNAPSHOT? If so we'll need to wait until that is released before we can release this quickstart, unless the SNAPSHOT version is available in some public maven repo?

**Comment by jimmidyson** [comment]
Building with 4.0 seems to mess up file paths in the Docker image as it uses my home dir for features location which isn't available in the image.

**Comment by jimmidyson** [comment]
Here's the output:

```
$  docker run --rm docker.io/fabric8/quickstart-karaf4-camellog:2.3-SNAPSHOT
I> No access restrictor found, access to all MBean is allowed
Jolokia: Agent started with URL http://172.17.0.8:8778/jolokia/
2015-08-08 18:46:47,299 | INFO  | FelixStartLevel  | fileinstall                      | 4 - org.apache.felix.file
install - 3.5.0 | Creating configuration from org.ops4j.pax.url.mvn.cfg
2015-08-08 18:46:47,314 | INFO  | FelixStartLevel  | fileinstall                      | 4 - org.apache.felix.file
install - 3.5.0 | Creating configuration from org.apache.karaf.log.cfg
2015-08-08 18:46:47,316 | INFO  | FelixStartLevel  | fileinstall                      | 4 - org.apache.felix.file
install - 3.5.0 | Creating configuration from org.apache.felix.fileinstall-deploy.cfg
2015-08-08 18:46:47,318 | INFO  | FelixStartLevel  | fileinstall                      | 4 - org.apache.felix.file
install - 3.5.0 | Creating configuration from org.apache.karaf.features.repos.cfg
2015-08-08 18:46:47,320 | INFO  | FelixStartLevel  | fileinstall                      | 4 - org.apache.felix.file
install - 3.5.0 | Creating configuration from org.apache.karaf.management.cfg
2015-08-08 18:46:47,671 | ERROR | pool-1-thread-1  | BootFeaturesInstaller            | 6 - org.apache.karaf.feat
ures.core - 4.0.0 | Error installing boot features
java.io.IOException: /home/jdyson/projects/fabric8-quickstarts/quickstarts/karaf4/camel-log/target/assembly/syste
m/org/apache/karaf/features/framework/4.0.0/framework-4.0.0-features.xml (No such file or directory) : file:/home
/jdyson/projects/fabric8-quickstarts/quickstarts/karaf4/camel-log/target/assembly/system/org/apache/karaf/feature
s/framework/4.0.0/framework-4.0.0-features.xml
        at org.apache.karaf.features.internal.service.RepositoryImpl.load(RepositoryImpl.java:85)[6:org.apache.ka
raf.features.core:4.0.0]
        at org.apache.karaf.features.internal.service.RepositoryImpl.load(RepositoryImpl.java:74)[6:org.apache.ka
raf.features.core:4.0.0]
        at org.apache.karaf.features.internal.service.FeaturesServiceImpl.getFeatures(FeaturesServiceImpl.java:63
6)[6:org.apache.karaf.features.core:4.0.0]
        at org.apache.karaf.features.internal.service.FeaturesServiceImpl.installFeatures(FeaturesServiceImpl.jav
a:828)[6:org.apache.karaf.features.core:4.0.0]
        at org.apache.karaf.features.internal.service.FeaturesServiceImpl.installFeatures(FeaturesServiceImpl.jav
a:771)[6:org.apache.karaf.features.core:4.0.0]
        at org.apache.karaf.features.internal.service.BootFeaturesInstaller.installBootFeatures(BootFeaturesInsta
ller.java:95)[6:org.apache.karaf.features.core:4.0.0]
        at org.apache.karaf.features.internal.service.BootFeaturesInstaller.start(BootFeaturesInstaller.java:76)[
6:org.apache.karaf.features.core:4.0.0]
        at org.apache.karaf.features.internal.osgi.Activator.doStart(Activator.java:257)[6:org.apache.karaf.featu
res.core:4.0.0]
        at org.apache.karaf.util.tracker.BaseActivator.run(BaseActivator.java:233)[6:org.apache.karaf.features.co
re:4.0.0]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)[:1.7.0_79]
        at java.util.concurrent.FutureTask.run(FutureTask.java:262)[:1.7.0_79]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)[:1.7.0_79]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)[:1.7.0_79]
        at java.lang.Thread.run(Thread.java:745)[:1.7.0_79]
Caused by: java.io.FileNotFoundException: /home/jdyson/projects/fabric8-quickstarts/quickstarts/karaf4/camel-log/
target/assembly/system/org/apache/karaf/features/framework/4.0.0/framework-4.0.0-features.xml (No such file or di
rectory)
        at java.io.FileInputStream.open(Native Method)[:1.7.0_79]
        at java.io.FileInputStream.<init>(FileInputStream.java:146)[:1.7.0_79]
        at java.io.FileInputStream.<init>(FileInputStream.java:101)[:1.7.0_79]
        at sun.net.www.protocol.file.FileURLConnection.connect(FileURLConnection.java:90)[:1.7.0_79]
        at sun.net.www.protocol.file.FileURLConnection.getInputStream(FileURLConnection.java:188)[:1.7.0_79]
        at java.net.URL.openStream(URL.java:1037)[:1.7.0_79]
        at org.apache.karaf.features.internal.service.RepositoryImpl.load(RepositoryImpl.java:80)[6:org.apache.ka
raf.features.core:4.0.0]
```

**Comment by dhirajsb** [comment]
Let me check with the Karaf team whether a fixed version of that plugin is
available. Alternatively, we could add the fusesource repo which has the
SNAPSHOT version to make it work for now.

**Comment by jimmidyson** [comment]
Fixed by using fusesource snapshot repo for karaf plugin.
