### ISSUE TITLE
Cannot fabric8:apply camel-servlet quickstart

### ISSUE THREAD

**Issue by rhuss** [fabric8io/quickstarts#664]
Calling `mvn clean package docker:build fabric8:apply -Dfabric8.recreate=true` in `camel-servlet` yields:

```
INFO] --- fabric8-maven-plugin:2.2.22:apply (default-cli) @ quickstart-war-camel-servlet ---
[INFO] Using kubernetes at: https://172.28.128.4:8443/api/v1/ in namespace default
[INFO] Kubernetes JSON: /Users/roland/Development/fabric8/quickstarts/quickstarts/war/camel-servlet/target/classes/kubernetes.json
[INFO] Is OpenShift: true
[INFO] Creating a namespace default
[INFO] Creating a template from kubernetes.json namespace default name quickstart-war-camel-servlet
[INFO] Created template: quickstarts/war/camel-servlet/target/fabric8/applyJson/default/template-quickstart-war-camel-servlet.json
[INFO] Deleting Service: quickstart-camelservlet
[INFO] Creating a service from kubernetes.json namespace default name quickstart-camelservlet
[INFO] Created service: quickstarts/war/camel-servlet/target/fabric8/applyJson/default/service-quickstart-camelservlet.json
[INFO] Creating a replicationController from kubernetes.json namespace default name quickstart-war-camel-servlet
[ERROR] Failed to create replicationController from kubernetes.json. io.fabric8.kubernetes.client.KubernetesClientException: ReplicationController "quickstart-war-camel-servlet" is invalid: spec.template.spec.containers[0].image: required value. ReplicationController(apiVersion=v1, kind=ReplicationController, metadata=ObjectMeta(annotations={}, creationTimestamp=null, deletionTimestamp=null, generateName=null, generation=null, labels={container=tomcat, component=quickstart-war-camel-servlet, provider=fabric8, group=quickstarts}, name=quickstart-war-camel-servlet, namespace=null, resourceVersion=null, selfLink=null, uid=null, additionalProperties={}), spec=ReplicationControllerSpec(replicas=1, selector={container=tomcat, component=quickstart-war-camel-servlet, provider=fabric8, group=quickstarts}, template=PodTemplateSpec(metadata=ObjectMeta(annotations={}, creationTimestamp=null, deletionTimestamp=null, generateName=null, generation=null, labels={container=tomcat, component=quickstart-war-camel-servlet, provider=fabric8, group=quickstarts}, name=null, namespace=null, resourceVersion=null, selfLink=null, uid=null, additionalProperties={}), spec=PodSpec(activeDeadlineSeconds=null, containers=[Container(args=[], command=[], env=[EnvVar(name=KUBERNETES_NAMESPACE, value=null, valueFrom=EnvVarSource(fieldRef=ObjectFieldSelector(apiVersion=null, fieldPath=metadata.namespace, additionalProperties={}), additionalProperties={}), additionalProperties={})], image=null, imagePullPolicy=null, lifecycle=null, livenessProbe=null, name=quickstart-war-camel-servlet, ports=[], readinessProbe=null, resources=null, securityContext=SecurityContext(capabilities=null, privileged=null, runAsNonRoot=null, runAsUser=null, seLinuxOptions=null, additionalProperties={}), terminationMessagePath=null, volumeMounts=[], workingDir=null, additionalProperties={})], dnsPolicy=null, host=null, hostNetwork=null, imagePullSecrets=[], nodeName=null, nodeSelector={}, restartPolicy=null, serviceAccount=null, serviceAccountName=null, terminationGracePeriodSeconds=null, volumes=[], additionalProperties={}), additionalProperties={}), additionalProperties={}), status=null, additionalProperties={})
io.fabric8.kubernetes.client.KubernetesClientException: ReplicationController "quickstart-war-camel-servlet" is invalid: spec.template.spec.containers[0].image: required value
	at io.fabric8.kubernetes.client.dsl.internal.BaseOperation.handleResponse(BaseOperation.java:465)
	at io.fabric8.kubernetes.client.dsl.internal.BaseOperation.handleCreate(BaseOperation.java:483)
	at io.fabric8.kubernetes.client.dsl.internal.BaseOperation.create(BaseOperation.java:153)
	at io.fabric8.kubernetes.api.Controller.doCreateReplicationController(Controller.java:791)
	at io.fabric8.kubernetes.api.Controller.applyReplicationController(Controller.j....
````

[ERROR] Failed to execute goal io.fabric8:fabric8-maven-plugin:2.2.22:apply (default-cli) on project quickstart-war-camel-servlet: Failed to create replicationController from kubernetes.json. io.fabric8.kubernetes.client.KubernetesClientException: ReplicationController "quickstart-war-camel-servlet" is invalid: spec.template.spec.containers[0].image: required value. ReplicationController(apiVersion=v1, kind=ReplicationController, metadata=ObjectMeta(annotations={}, creationTimestamp=null, deletionTimestamp=null, generateName=null, generation=null, labels={container=tomcat, component=quickstart-war-camel-servlet, provider=fabric8, group=quickstarts}, name=quickstart-war-camel-servlet, namespace=null, resourceVersion=null, selfLink=null, uid=null, additionalProperties={}), spec=ReplicationControllerSpec(replicas=1, selector={container=tomcat, component=quickstart-war-camel-servlet, provider=fabric8, group=quickstarts}, template=PodTemplateSpec(metadata=ObjectMeta(annotations={}, creationTimestamp=null, deletionTimestamp=null, generateName=null, generation=null, labels={container=tomcat, component=quickstart-war-camel-servlet, provider=fabric8, group=quickstarts}, name=null, namespace=null, resourceVersion=null, selfLink=null, uid=null, additionalProperties={}), spec=PodSpec(activeDeadlineSeconds=null, containers=[Container(args=[], command=[], env=[EnvVar(name=KUBERNETES_NAMESPACE, value=null, valueFrom=EnvVarSource(fieldRef=ObjectFieldSelector(apiVersion=null, fieldPath=metadata.namespace, additionalProperties={}), additionalProperties={}), additionalProperties={})], image=null, imagePullPolicy=null, lifecycle=null, livenessProbe=null, name=quickstart-war-camel-servlet, ports=[], readinessProbe=null, resources=null, securityContext=SecurityContext(capabilities=null, privileged=null, runAsNonRoot=null, runAsUser=null, seLinuxOptions=null, additionalProperties={}), terminationMessagePath=null, volumeMounts=[], workingDir=null, additionalProperties={})], dnsPolicy=null, host=null, hostNetwork=null, imagePullSecrets=[], nodeName=null, nodeSelector={}, restartPolicy=null, serviceAccount=null, serviceAccountName=null, terminationGracePeriodSeconds=null, volumes=[], additionalProperties={}), additionalProperties={}), additionalProperties={}), status=null, additionalProperties={}) -> [Help 1]
[ERROR]

**Comment by rhuss** [comment]
Forgot: I'm using the newest Vagrant OpenShift image with OpenShift3 1.0.4 and Kubernetes 1.0.0

**Comment by rhuss** [comment]
forgot to add `docker.image` property, shame on me :)
